### ISSUE TITLE
Transaction Error being treated as a successful transaction

### ISSUE THREAD

**Issue by LavaToaster** [digitickets/omnipay-verifone-web-service#1]
If Verifone's transaction response returns a `MsgType` of `ERROR` during the transaction the `PurchaseResponse` doesn't deal with it, it only checks for transaction failure - and on top of that only deals with known failure modes, any unknown failure modes are skipped by it.

This did occur on the system I tried implementing this in, it had managed to create the card token but the transaction request error'ed out.

This was the Non-Session based gateway.

**Comment by pedanticantic** [comment]
Hi,

Sorry for the delay in replying.

It's strange you're having a problem as the non-session-based gateway has been certified by Verifone. Of course, I'll look into it. I'm actually on leave this week, so I won't be able to look until next week. In the mean time, would you be able to supply an example transaction response? If you wanted to fix it yourself and create a Pull Request, I'll be happy to merge it in.

Regarding the "known failure modes", I think I see what you're saying. It's in DigiTickets\VerifoneWebService\Message\NonSessionBased\PurchaseResponse::getError(), where it tests whether the result is in the list of failure statuses. It should test that it's _not_ in a list of known success statuses (I'm not sure why I did it that way round - I'm normally make things fail safe). I will fix this next week.

Regards,
\- Glenn -

**Comment by pedanticantic** [comment]
Sorry for the delay in replying. I looked, and the reason why it was a blacklist is that during Verifone's testing, they'd said, "You don't fail transactions with these statuses: 'REFERRAL', 'DECLINED', and 'COMMSDOWN'", so I added them as a blacklist without really thinking.

Also, recently, we started getting responses with a txnresult of 'ERROR' and the driver wasn't rejecting them (ie exactly the problem you had reported), so I decided to change it to a whitelist.

The fix is available from v1.0.4

Regards,
\- Glenn -
